### ISSUE TITLE
Erro para compilação.

### ISSUE THREAD

**Issue by Lvitor** [wilsonfreitas/rb3#11]
Estou recebendo esse erro na instalação do pacote:

Error: Failed to install 'rbmfbovespa' from GitHub:
  System command error, exit status: 1, stdout + stderr:
E> * checking for file 'C:\Users\pc\AppData\Local\Temp\RtmpIrueqA\remotes34b05eb278d9\wilsonfreitas-rbmfbovespa-9f6622b/DESCRIPTION' ... OK
E> * preparing 'rbmfbovespa':
E> * checking DESCRIPTION meta-information ... OK
E> Warning in grepl(e, files, perl = TRUE, ignore.case = TRUE) :
E>   erro de compilação de padrão PCRE
E> 	'nothing to repeat'
E> 	at '*.json'
E> Error in grepl(e, files, perl = TRUE, ignore.case = TRUE) : 
E>   expressão regular inválida '*.json'
E> Execução interrompida

tem como me ajudar? Obrigado.

**Comment by jozephbrasil** [comment]
Estou tendo este mesmo problema. Será que você poderia dar uma luz do que fez para resolver?

**Comment by rvedra** [comment]
Mesmo problema aqui. Alguém consegue ajudar?

**Comment by wilsonfreitas** [comment]
Qual versão do R vcs estão usando?

**Comment by rvedra** [comment]
Atualizei para a versão 1.3.959 recentemente.

**Comment by jozephbrasil** [comment]
> Qual versão do R vcs estão usando?

Estou usando a versão 4.0.0.

**Comment by jozephbrasil** [comment]
Atualizei pra 4.0.1 e mesmo erro.

**Comment by wilsonfreitas** [comment]
Não fiz atualização desse pacote para a versão 4 do R. Vou fazer isso e aviso sobre a evolução.

**Comment by wilsonfreitas** [comment]
Atualizei os projetos `transmute` e `rb3` (`rbmfbovespa`  renomeado).

Para instalar.

```
devtools::install_github('wilsonfreitas/transmute')
devtools::install_github('wilsonfreitas/rb3')
```

Testei no R 4.0.1 no Windows 10.
