### ISSUE TITLE
Arquivos .txt são todos públicos

### ISSUE THREAD

**Issue by msperlin** [wilsonfreitas/rb3#16]
Notei que os arquivos .TXT que o pacote lê são todos públicos, basta buscar a url. Por exepmlo:

https://download.bmfbovespa.com.br/FTP/IPNv2/RISCO/CenariosTipoPrecoReferencial220411.zip

Uma ideia é montarmos uma função que baixa os arquivos, os quais são posteriormente lidos pelas outras funções.

**Comment by msperlin** [comment]
Aqui o ftp utilizado:

https://download.bmfbovespa.com.br/FTP/IPNv2/RISCO/

**Comment by wilsonfreitas** [comment]
Muito bom, ainda não tem o template para estes arquivos, mas é tranquilo construir.
Nestes arquivos de cenários o cenário 1 é o cenário base, cenário sem choques, a própria cotação dos ativos, e os demais dados são cenários utilizados no CORE.
Talvez seja legal separar isso.

BTW vou precisar mexer nas classes de template que montei, o CRAN CHECK está reclamando das strings unicode.
Já acertei os demais erros/avisos/notas só falta esse e resolvendo isso já podemos submeter ao CRAN.

**Comment by msperlin** [comment]
Vou dar uma pesquisada mais a fundo, e ver quais dados .TXT estão disponíveis. Notei que o ftp mencionado acima fornece dados com uma janela curta de tempo (menos de um ano). 

Sobre o cran, boa. Vamos adicionar mais coisas tb antes:
- githhub actions para CHECK/pkgdown/coverage
- coverage tests
- metacode.json

Vamos falando.
