### ISSUE TITLE
Indexes information

### ISSUE THREAD

**Issue by wilsonfreitas** [wilsonfreitas/rb3#29]
An implementation like these examples from tidyquant

```r
# Load libraries
library(tidyquant)

# Get the list of stock index options
tq_index_options()

# lists all symbols in the given index
tq_index("DOW")
```

**Comment by msperlin** [comment]
I have that from yfR:

`yfR::yf_get_index_comp("SP500")`

you can check available indices with:

yfR::yf_get_available_indices()

Perhaps would be smart to write a single package for this particular problem? And use in both packages?

**Comment by wilsonfreitas** [comment]
This information can be obtained with the template GetStockIndex that returns a dataframe like

```r
r$> f <- download_data("GetStockIndex")
r$> df <- read_marketdata(f, "GetStockIndex", FALSE)
r$> head(df)
#>        company spotlight   code                                 indexes     update start_month end_month year
#> 1           3M       DRN MMMC34                                    BDRX 2022-04-14           1         4 2022
#> 2 3R PETROLEUM   ON   NM  RRRP3 IBOV,IBRA,IBXX,IGCT,IGCX,IGNM,ITAG,SMLL 2022-04-14           1         4 2022
#> 3      3TENTOS   ON   NM  TTEN3      IBRA,ICON,IGCT,IGCX,IGNM,ITAG,SMLL 2022-04-14           1         4 2022
#> 4     AB INBEV       DRN ABUD34                                    BDRX 2022-04-14           1         4 2022
#> 5      ABB LTD       DRN A1BB34                                    BDRX 2022-04-14           1         4 2022
#> 6       ABBOTT       DRN ABTT34                                    BDRX 2022-04-14           1         4 2022
```

The idea here is an abstraction similar to `tidyquant::tq_index`

```r
index_get(df, "IBOV")
index_get(df, "BDRX")
```

**Comment by wilsonfreitas** [comment]
New functions to get indexes information (composition, weights and positions)

  * `index_comp_get` returns the index composition
  * `index_weights_get` returns the index weights
  * `index_by_segment_get` returns indexes assets grouped by segments
  * `indexes_get` lists the available indexes
  * `indexes_last_update` returns the date when the indexes have been updated
