### ISSUE TITLE
Scrape "IBOVESPA Evolução diária"

### ISSUE THREAD

**Issue by wilsonfreitas** [wilsonfreitas/rb3#39]
This spreadsheet has data ranging from 1968-1997
[IBOVDIA.XLS](https://github.com/wilsonfreitas/rb3/files/8881749/IBOVDIA.XLS)

The rest can be obtained with this url.

<https://sistemaswebb3-listados.b3.com.br/indexStatisticsPage/daily-evolution/IBOV>

This URL can be used with other indexes.

**Comment by msperlin** [comment]
Fantástico isso aqui heim!

**Comment by msperlin** [comment]
Estou enrolado essa semana (comecou o semestre), mas posso tentar implementar assim que tiver um tempo.

**Comment by wilsonfreitas** [comment]
Done
