### ISSUE TITLE
Coluna 

### ISSUE THREAD

**Issue by Lvitor** [wilsonfreitas/rb3#42]
Olá, 

Na a função read_marketdata, template=  'COTAHIST_YEARLY' a coluna  qtd_titulos_negociados   esta com tipo caractere ao invés de numérico. 

Abraços

**Comment by wilsonfreitas** [comment]
Sim,

Isso foi corrigido em 645a835c2e2811bd97987c351a5ab00812cb497a.

Sairá na próxima versão do pacote 0.0.4.
