### ISSUE TITLE
Filtrar apenas 1 vértice da ETTJ com o "yc_mget"

### ISSUE THREAD

**Issue by GuilhermeStipp** [wilsonfreitas/rb3#45]
Olá pessoal, boa tarde!

Existe a possibilidade de ao invés a função `yc_mget` puxar a curva nominal de diversos dias úteis, puxar apenas um vértice específico, por exemplo o vértice 252?

Muito obrigado.

**Comment by wilsonfreitas** [comment]
Apenas adicionando um ponto a resposta do Marcelo que está 100% correta.

Não há como "puxar" apenas 1 vértice, uma vez que fazemos web scraping no HTML que contém todos os vértices.

**Comment by GuilhermeStipp** [comment]
Muito obrigado pelas respostas pessoal. @msperlin o problema é que tanto para a curva DI x pré quanto para a DI x IPCA, não são todos os dias que é divulgado o vértice específico. Filtrando esses dados, se perde muitas observações. Acredito que uma forma de resolver isso é usar o pacote `fixedincome `do @wilsonfreitas para interpolar os dados faltantes no HTML da B3.

**Comment by wilsonfreitas** [comment]
A B3 divulga os vértices utilizados no apreçamento dos seus diversos contratos, logo, se você precisa de um vértice específico, eventualmente haverão datas nas quais este vértice não existe.
A melhor alternativa para a construção de uma base com vértices pré-definidos é utilizando os futuros e, como você mencionou, utilizar `fixedincome` para fazer a interpolação.
Por 2 motivos:

- O histórico de taxas referencias, de onde pegamos as curvas, não é muito longo, volta até 2018, se não me engano.
- Se utilizar o histórico de curvas para interpolação, essa interpolação será realizada sobre a curva com os vértices que já foram interpolados, é uma interpolação sobre uma interpolação, e isso pode gerar resultados incorretos.

Neste [post](https://www.wilsonfreitas.net/posts/2022-06-18-16-anos-de-curva-prefixada/) eu mostro como utilizar os dados de futuros para a construção de curvas de juros e faço isso para um histórico que começa em 2007.

Com essa base você pode criar uma lista com as curvas e realizar a interpolação nos vértices que deseja.
